// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BaseSearchInput: typeof import('./src/components/BaseSearchInput.vue')['default']
    IBxBxSearch: typeof import('~icons/bx/bx-search')['default']
    Tested: typeof import('./src/components/Tested.vue')['default']
  }
}

export { }
